#!/bin/bash

if [ -v BBV_DIR ]; then
  BBV_OPT=-Q "$BBV_DIR"
fi

set -ex
make -C lib

coqc $BBV_OPT -Q lib Sail -Q arm SailArm arm/aarch64_extras.v
coqc $BBV_OPT -Q lib Sail -Q arm SailArm arm/aarch64_types.v
coqc -time $BBV_OPT -Q lib Sail -Q arm SailArm arm/aarch64.v
